### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by agileurbanite** [DanWahlin/AngularIn20TypeScript#1]
Hey Dan, heard your talk at ngconf2015 and it was cool, but I missed how to add these Typescript libraries or plugins.  I tried running tsd reinstall but I'm missing tsd.d.ts.  I was hoping you can update the Readme.md with an updated documentation on getting started.  Thanks again and really appreciate your work on educating the community on Angular and Typescript!

**Comment by gintsgints** [comment]
Second for that....

**Comment by DanWahlin** [comment]
I'm out on vacation so I'll have to revisit this but here's what's in the tsd.d.ts file. It should be placed in the tools/typings folder.

```
/// <reference path="angularjs/angular.d.ts" />
/// <reference path="angularjs/angular-route.d.ts" />
/// <reference path="angularjs/angular-animate.d.ts" />
/// <reference path="jquery/jquery.d.ts" />
```

**Comment by gintsgints** [comment]
Ok. simple 

```
tsd update
```

worked for me.
