### ISSUE TITLE
install seems to be missing typescriptApp.d.ts

### ISSUE THREAD

**Issue by MichaelChambers** [DanWahlin/AngularIn20TypeScript#10]
Hi, I'm new to Angular and Typescript and was hoping to install this to start figuring things out. After running all the install commands and starting superstatic, IE11 opened with an error.

Fiddler shows 404s for all /js/*_/_.js files (no wonder IE had errors!)

From the gulp errors, the root cause appears that it could not compile the app's typescript files due to not finding typescriptApp.d.ts. I don't see a file named that anywhere in the directories.
The final result of the gulp errors is that I have no directory src/js next to src/app

Here's the end of the command line log including the gulp errors:
...(removed above and submodules from the following for brevity)
gulp-sourcemaps@1.5.2 node_modules\gulp-sourcemaps
del@1.2.0 node_modules\del
gulp-debug@2.0.1 node_modules\gulp-debug
gulp-inject@1.3.1 node_modules\gulp-inject
gulp@3.9.0 node_modules\gulp
superstatic@2.2.1 node_modules\superstatic
gulp-typescript@2.7.8 node_modules\gulp-typescript
tsd@0.5.7 node_modules\tsd
gulp-tslint@1.5.0 node_modules\gulp-tslint
gulp-tsd@0.0.4 node_modules\gulp-tsd

C:\ang\ang1.4\AngularIn20TypeScript>bower install
bower angular-animate#1.4.0 not-cached git://github.com/angular/bower-angular-animate.git#1.4.0
bower angular-animate#1.4.0    resolve git://github.com/angular/bower-angular-animate.git#1.4.0
bower angular#1.4.0         not-cached git://github.com/angular/bower-angular.git#1.4.0
bower angular#1.4.0            resolve git://github.com/angular/bower-angular.git#1.4.0
bower bootstrap#3.2.0           cached git://github.com/twbs/bootstrap.git#3.2.0
bower bootstrap#3.2.0         validate 3.2.0 against git://github.com/twbs/bootstrap.git#3.2.0
bower angular-bootstrap#0.10.0       not-cached git://github.com/angular-ui/bootstrap-bower.git#0.10.0
bower angular-bootstrap#0.10.0          resolve git://github.com/angular-ui/bootstrap-bower.git#0.10.0
bower angular-route#1.4.0            not-cached git://github.com/angular/bower-angular-route.git#1.4.0
bower angular-route#1.4.0               resolve git://github.com/angular/bower-angular-route.git#1.4.0
bower angular-bootstrap#0.10.0         download https://github.com/angular-ui/bootstrap-bower/archive/0.10.0.tar.gz
bower angular#1.4.0                    download https://github.com/angular/bower-angular/archive/v1.4.0.tar.gz
bower angular-animate#1.4.0            download https://github.com/angular/bower-angular-animate/archive/v1.4.0.tar.gz
bower angular-route#1.4.0              download https://github.com/angular/bower-angular-route/archive/v1.4.0.tar.gz
bower jquery#>= 1.9.0                    cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#>= 1.9.0                  validate 2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.0
bower angular-bootstrap#0.10.0          extract archive.tar.gz
bower angular-bootstrap#0.10.0     invalid-meta angular-bootstrap is missing "ignore" entry in bower.json
bower angular-bootstrap#0.10.0         resolved git://github.com/angular-ui/bootstrap-bower.git#0.10.0
bower angular-animate#1.4.0             extract archive.tar.gz
bower angular-animate#1.4.0            resolved git://github.com/angular/bower-angular-animate.git#1.4.0
bower angular-route#1.4.0               extract archive.tar.gz
bower angular-route#1.4.0              resolved git://github.com/angular/bower-angular-route.git#1.4.0
bower angular#1.4.0                     extract archive.tar.gz
bower angular#1.4.0                    resolved git://github.com/angular/bower-angular.git#1.4.0
bower angular                  extra-resolution Unnecessary resolution: angular#1.4.0
bower bootstrap#3.2.0                   install bootstrap#3.2.0
bower angular-bootstrap#0.10.0          install angular-bootstrap#0.10.0
bower angular-animate#1.4.0             install angular-animate#1.4.0
bower jquery#>= 1.9.0                   install jquery#2.1.4
bower angular-route#1.4.0               install angular-route#1.4.0
bower angular#1.4.0                     install angular#1.4.0

bootstrap#3.2.0 src\bower_packages\bootstrap
+-- jquery#2.1.4

angular-bootstrap#0.10.0 src\bower_packages\angular-bootstrap
+-- angular#1.4.0

angular-animate#1.4.0 src\bower_packages\angular-animate
+-- angular#1.4.0

jquery#2.1.4 src\bower_packages\jquery

angular-route#1.4.0 src\bower_packages\angular-route
+-- angular#1.4.0

angular#1.4.0 src\bower_packages\angular

C:\ang\ang1.4\AngularIn20TypeScript>tsd reinstall -so

-> running reinstall

> > written 4 files:

```
- angularjs/angular-animate.d.ts
- angularjs/angular-route.d.ts
- angularjs/angular.d.ts
- jquery/jquery.d.ts
```

C:\ang\ang1.4\AngularIn20TypeScript>gulp
[13:02:03] Using gulpfile C:\ang\ang1.4\AngularIn20TypeScript\gulpfile.js
[13:02:03] Starting 'ts-lint'...
[13:02:03] Starting 'compile-ts'...
[13:02:03] Starting 'gen-ts-refs'...
[13:02:03] Starting 'watch'...
[13:02:03] Finished 'watch' after 11 ms
[13:02:03] Finished 'gen-ts-refs' after 31 ms
[13:02:03] Finished 'ts-lint' after 210 ms
src\app\app.module.ts(2,1): error TS6053: File 'C:/ang/ang1.4/AngularIn20TypeScript/tools/typings/typescriptApp.d.ts' not found.
src\app\controllers\customers.controller.ts(2,1): error TS6053: File 'C:/ang/ang1.4/AngularIn20TypeScript/tools/typings/typescriptApp.d.ts' not found.
src\app\controllers\orders.controller.ts(2,1): error TS6053: File 'C:/ang/ang1.4/AngularIn20TypeScript/tools/typings/typescriptApp.d.ts' not found.
src\app\directives\filterTextbox.directive.ts(2,1): error TS6053: File 'C:/ang/ang1.4/AngularIn20TypeScript/tools/typings/typescriptApp.d.ts' not found.
src\app\services\customers.service.ts(2,1): error TS6053: File 'C:/ang/ang1.4/AngularIn20TypeScript/tools/typings/typescriptApp.d.ts' not found.
[13:02:03] TypeScript: 5 syntax errors
[13:02:03] TypeScript: emit failed
[13:02:03] Finished 'compile-ts' after 419 ms
[13:02:03] Starting 'default'...
[13:02:03] Finished 'default' after 50 µs
^CTerminate batch job (Y/N)? y

C:\ang\ang1.4\AngularIn20TypeScript>ss

**Comment by MichaelChambers** [comment]
OK, the missing file had been marked as deleted from git. I'm not sure how that happened, but I managed to pull it down again and now I have my JS files.

C:\ang\ang1.4\AngularIn20TypeScript>git checkout
M       tools/typings/tsd.d.ts
D       tools/typings/typescriptApp.d.ts
Your branch is up-to-date with 'origin/master'.

C:\ang\ang1.4\AngularIn20TypeScript>git reset HEAD tools/typings/typescriptApp.d.ts
Unstaged changes after reset:
M       tools/typings/tsd.d.ts
D       tools/typings/typescriptApp.d.ts

C:\ang\ang1.4\AngularIn20TypeScript>git checkout  -- tools/typings/typescriptApp.d.ts

C:\ang\ang1.4\AngularIn20TypeScript>gulp
[13:57:15] Using gulpfile C:\ang\ang1.4\AngularIn20TypeScript\gulpfile.js
[13:57:15] Starting 'ts-lint'...
[13:57:15] Starting 'compile-ts'...
[13:57:15] Starting 'gen-ts-refs'...
[13:57:15] Starting 'watch'...
[13:57:15] Finished 'watch' after 9.56 ms
[13:57:15] gulp-inject 5 files into typescriptApp.d.ts.
[13:57:15] Finished 'gen-ts-refs' after 148 ms
[13:57:15] Finished 'ts-lint' after 192 ms
[13:57:16] Finished 'compile-ts' after 985 ms
[13:57:16] Starting 'default'...
[13:57:16] Finished 'default' after 8.45 µs

**Comment by donovanmuller** [comment]
:+1:

**Comment by DanWahlin** [comment]
The typescriptApp.d.ts should have been pulled down automatically since it's in the source code. Not sure what happened as you pulled it down but glad you got it going.
