### ISSUE TITLE
Generate tsd files?

### ISSUE THREAD

**Issue by jahnreektor** [DanWahlin/AngularIn20TypeScript#4]
Thanks for creating this example!

I'm trying to figure out how to generate the TSD files.  Running gulp reveals he following error:

```
[00:42:09] Finished 'gen-ts-refs' after 95 ms
src/app/app.module.ts(1,1): 6053 File '/home/ubuntu/pro-angular-js/AngularIn20TypeScript/tools/typings/tsd.d.ts' not found.
src/app/app.module.ts(2,1): 6053 File '/home/ubuntu/pro-angular-js/AngularIn20TypeScript/tools/typings/typescriptApp.d.ts' not found.
src/app/controllers/customers.controller.ts(1,1): 6053 File '/home/ubuntu/pro-angular-js/AngularIn20TypeScript/tools/typings/tsd.d.ts' not found.
[...]
```

I can manually install the TSD files for angular/jquery/etc, but it seems these particular missing TSD files are custom.  Is that right?

I'm relatively new to this environment, so it's entirely plausible that I messed up something.  Thanks.

**Comment by jessecravens** [comment]
I think Im seeing the same issue. I can install all but custom TSDs.
$ tsd update -so

-> running update

> > written 4 files:

```
- angularjs/angular-animate.d.ts
- angularjs/angular-route.d.ts
- angularjs/angular.d.ts
- jquery/jquery.d.ts
```

Would be ideal if similar to npm, could just run:

$ tsd intall

to install local deps from the tsd.json.

**Comment by DanWahlin** [comment]
At this point you need to run tsd update -so to generate the proper tsd file. They'll get added into the tools/typings folder.
